# Generated by Django 3.2.6 on 2021-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0003_auto_20211206_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
