# Generated by Django 3.2.6 on 2021-12-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0004_alter_journalist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
