# Generated by Django 3.2.6 on 2021-12-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0005_alter_journalist_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalist',
            old_name='author',
            new_name='name',
        ),
    ]
