# Generated by Django 3.2.6 on 2021-12-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_book', '0006_rename_author_journalist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalist',
            old_name='name',
            new_name='author',
        ),
    ]
